kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-validating-webhook
webhooks:
  - name: validating-webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore
    rules:
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*/*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVQkVGZFB0T0FyaE9oYTR5ZlVweDZwSS9uM05zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSXdNRFV5TnpJeU1UVXdObG9ZRHpJeQpPVFF3TXpFeU1qSXhOVEEyV2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM2eERPZytBZkRCMjZYb1ZBR0ZWUzR3WmJsV1VtQmVoYXQKZlEvbmdFYkRPb3h0NldrdEtkSzRieXNiM05UVnpJdlhPYXQrOG82V240MEMrQVlBTlN1YWwxeFpxUTNRQnBKaQp6STZjQ0ZNd3ZOSGxFSVZPSXorSERQS0lncVJBU0tobFI1ZzV6ZGp4eWNiVWJoNXg5VFlZSzk3ZzVra2RKMS9ICktlQUZUdkgza2greUJ2MUJvcEJYd2szM2UrcjVpdWdMbVBGTEMvUkpVNk1LYTFOYkxab3VuRS80NmRGYTBVZEwKdFhNOExFaTVqL200M1FsejN5VDJPVm9qM3VGWEZQSE91OEJPT25uUVZEcFhxYjVzSWErQmRuSmZvWUQ1YndtQQpBeHZ1elcrVWNpWmMydFg4a1JxWkVBMCtNdnIyelVMNm9IVUI0Y3RTcFNTQ2FjSFlQMW5uQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCU05KYTVJVXAzNlV1dmV1Z1A2T042QVlxZDFJREFmQmdOVkhTTUVHREFXZ0JTTkphNUkKVXAzNlV1dmV1Z1A2T042QVlxZDFJREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFBYWNtQXV3UmdQMXdwQm5vclh4OUZXMW13cUIrNXBWM0ZRSWxqSkkzN1RFZmt3VjJ2aFd0QUZHNDh2CmowdnVtNHVzZXdMVjZZdngrZCtzV3ZMODlzRFlMcjEzVHlDU1AwVXFpWmlEV3VDUXdlMkJEY2dIT2FGaDdSVUgKalNzOWE2YWtKbXZRa2tqTXZPS09WejNHb2NhRDJhWDlpSkNsQzZudk12MGdwbWE1WW5RUGNQMWpMbDlBVkNUcApYMjE5aVJ5c3hnRG1TR1Y0UnpIVWxQZ2ZQS0tQbGpuWTMyblZCTFFSTnU4clVRTmhNUmpzVW9KNjBGR2x0UzZ4CnlUSmRzVm1lLzZmKzNDSG9kOHdpV2pKNmgvU3JYaWRwQXc4amNiRlpOZ2RVS3BwUDJyVVRJU3BQN0VncTBlcksKL2JsMWJGMzd6a0ZOYzhYVE5JMDVaWGoyRjJpWQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: opa
        name: opa
